apiVersion: v1
kind: Secret
metadata:
  name: redbus-secrets
  namespace: redbus
type: Opaque
stringData:
  POSTGRES_PASSWORD: "123"
  DB_PASSWORD: "123"
  ADMIN_EMAIL: "redbus@example.com"
  ADMIN_PASSWORD: "SecurePassword123!"
  DOCKER_HUB_USERNAME: "rahulraman"
  DOCKER_HUB_PASSWORD: "your-docker-hub-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: redbus
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJyYWh1bHJhbWFuIiwicGFzc3dvcmQiOiJ5b3VyLWRvY2tlci1odWItdG9rZW4iLCJhdXRoIjoiY0hKbGNHNXBibWR2T1hkemRHOXdkR1Z1WjI4PSJ9fQ==
---
# Secret for Elasticsearch
apiVersion: v1
kind: Secret
metadata:
  name: elk-credentials
  namespace: redbus
type: Opaque
stringData:
  ELASTIC_PASSWORD: "elastic123"
  KIBANA_PASSWORD: "kibana123"
  LOGSTASH_PASSWORD: "logstash123"
