pipeline {
    agent any
    
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub-credentials')
        DOCKER_HUB_USERNAME = 'rahulraman'
        SERVICE_NAME = 'eureka-server'
        IMAGE_NAME = "${DOCKER_HUB_USERNAME}/redbus-${SERVICE_NAME}:latest"
        GIT_REPO = 'https://github.com/Rahul09123/Red-Bus.git'
        PATH = "/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${GIT_REPO}"
            }
        }
        stage('Build') {
            steps {
                dir("backend/${SERVICE_NAME}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir("backend/${SERVICE_NAME}") {
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh """
                    echo \$DOCKER_HUB_CREDENTIALS_PSW | docker login -u \$DOCKER_HUB_CREDENTIALS_USR --password-stdin
                    docker push ${IMAGE_NAME}
                    docker logout
                """
            }
        }
    }
    post {
        always { cleanWs() }
    }
}
